name: flex_form

packages:
  - ./demo
  - .

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        'flutter analyze . --fatal-infos'
    description: |
      Run `flutter analyze` in all packages.

  lint:all:
    run: melos run analyze
    description: Run all static analysis checks.

  test:
    run: |
      melos exec -c 1 --fail-fast -- \
        'flutter test --no-pub'
    description: Run `flutter test` for all packages.

  test:select:
    run: |
      melos exec -- 'flutter test'
    packageFilters:
      scope: '*'

  build:form:
    run: |
      melos exec --fail-fast --scope='flex_form' -- \
        'flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs'

  clean-build:form:
    run: |
      melos exec --fail-fast --scope='flex_form' 'flutter clean' \
      && melos run build:form

  build:form-demo:
    run: |
      melos exec --fail-fast --scope='flex_form_demo' -- \
        'flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs'

  clean-build:form-demo:
    run: |
      melos exec --fail-fast --scope='flex_form_demo' 'flutter clean' \
      && melos run build:form-demo
